INSERT INTO PopularAttractions (id_attraction, name_attraction, in_WHS, id_city) VALUES
(1, 'Lincoln Memorial', FALSE, 1),
(2, 'Statue of Liberty', TRUE, 2),
(3, 'National Mall', FALSE, 1),
(4, 'Times Square', FALSE, 2),
(5, 'Zocalo', FALSE, 3),
(6, 'Chichen Itza', TRUE, 4),
(7, 'Parliament Hill', FALSE, 5),
(8, 'CN Tower', FALSE, 6),
(9, 'Old Havana', TRUE, 7),
(10, 'Varadero Beach', FALSE, 8),
(11, 'National Palace of Culture', FALSE, 9),
(12, 'Antigua Guatemala Ruins', TRUE, 10),
(13, 'Cathedral of Managua', FALSE, 11),
(14, 'Granada Cathedral', FALSE, 12),
(15, 'National Theatre of Costa Rica', FALSE, 13),
(16, 'Africa Mia Safari Park', FALSE, 14),
(17, 'Panama Canal', FALSE, 15),
(18, 'Alcazar de Colon', TRUE, 16),
(19, 'Boca Chica Beach', FALSE, 17),
(20, 'Sans-Souci Palace', TRUE, 18),
(21, 'Devon House', FALSE, 19),
(22, 'Atlantis Paradise Island', FALSE, 20),
(23, 'Bridgetown Harbour', FALSE, 21),
(24, 'St. John Cathedral', FALSE, 22),
(25, 'Fort George', FALSE, 23),
(26, 'Morne Trois Pitons National Park', TRUE, 24),
(27, 'Pigeon Island National Landmark', FALSE, 25),
(28, 'Botanical Gardens', FALSE, 26),
(29, 'Queen Park Savannah', FALSE, 27),
(30, 'Belize Zoo', FALSE, 28),
(31, 'Hol Chan Marine Reserve', FALSE, 29),
(32, 'Metropolitan Cathedral', FALSE, 30),
(33, 'Honduras Maya Archaeological Site', TRUE, 31),
(34, 'El Yunque National Forest', FALSE, 32),
(35, 'Castillo Serralles', FALSE, 33),
(36, 'Golden Gate Bridge', FALSE, 34),
(37, 'Millennium Park', FALSE, 35),
(38, 'Space Needle', FALSE, 36),
(39, 'Stanley Park', FALSE, 37),
(40, 'Citadelle of Quebec', TRUE, 38),
(41, 'Palancar Reef', FALSE, 39),
(42, 'Doctor Cave Beach Club', FALSE, 40),
(43, 'Red Frog Beach', FALSE, 41),
(44, 'Altos de Chavón', FALSE, 42),
(45, 'Aruba Aloe Museum & Factory', FALSE, 43),
(46, 'Dunn River Falls', FALSE, 44),
(47, 'Todos Santos Plaza', FALSE, 45),
(48, 'La Bufadora', FALSE, 46),
(49, 'Xcaret Park', FALSE, 47),
(50, 'Caroni Bird Sanctuary', FALSE, 48),
(51, 'Waterloo', FALSE, 49),
(52, 'Jambay', FALSE, 50),
(53, 'Cloud Gate', FALSE, 35),
(54, 'Empire State Building', FALSE, 2);

